[SystemParameter]
;719定制是否判断打开软件后自动进行采集
IsNeedCheckSampleStartTime=0

;软件打开后未自动进行采集的时间(s)
CheckSampleStartTimeValue=600

;是否保留未响应框（用于软件异常后自启动出现未响应提示框），0代表不保留，kill该进程；1代表保留未响应框进程
isRetainUnRespondInfo = 0

;DHDAS程序异常运行监控工具获取间隔时间(s)
ReadProcessTime = 300

;当前监控程序的名称(运行程序需在DHDAS安装目录下)(格式示例：目录名称\程序名称 注：可不包含目录名称，程序名称不需要带后缀名,使用英文逗号隔开(,))
MonitorRunSoftName=DHDAS

;软件未打开定时监测时间(s)
ExistSoftwareTimeFirst = 120
ExistSoftwareTime = 5