[TCPClientOutData]
ServerCount = 1 ;服务端个数
ServerIp0 = 127.0.0.1
ServerPort0 = 6003
ParseType0 = 1
ChannelCount0 = 8
[TCPServerOutData]
ClientCount = 1 ;客户端台数
ClientIp0 = 127.0.0.1
ParseType0 = 1
ChannelCount0 = 8
[5955CustomFunc]
;5955/千兆网平台下位机定制功能使用参数 = 
;磁盘保持最小剩余空间 = 
DiskMinFreeSpace = 0
;存盘工程管理 = 
StoreProjectManage = 0
;数据存储分工程 = 
DataStoreSplitPrj = 0
;下位机启动时，固定测量类型 = 
StartFixMeasureType = 0
;固定测量类型 = 
FixMeasureType = 2
;下位机启动时，读Teds = 
StartReadTeds = 0
;下位机启动时，平衡结果下传，零点设置 = 
StartDownBalanceAndZero = 0
;下位机启动时，使用上一次的采样状态 = 
StartUseLastSampleStatus = 0
;最近一次受控的采样状态 = 
LastControlSampling = 0
;下位机启动时，使用上一次的受控的网络协议模式 0 - 下位机默认DHDAS控制 = 
StartUseLastProtolMode = 0
;受控的网络协议模式 0 - DHDAS; 1 - PHM = 
ControlProtocolMode = 0
;实时回收丢包数据单次发送字节 = 
RealTimeSendLostBytes = 4096
[SystemParameter]
;地面监控目的ip = 
EarthSurfaceMonitorDesIP = 192.168.1.45
EarthSurfaceMonitorSrcIP = 192.168.1.85
;地面监控目的端口 = 
EarthSurfaceMonitorDesPort = 1000
EarthSurfaceMonitorSrcPort = 1000
;地面运控目的ip = 
EarthSurfaceOperationControlDesIP = 172.16.1.12
EarthSurfaceOperationControlSrcIP = 172.16.1.121
;地面运控目的端口 = 
EarthSurfaceOperationControlDesPort = 10060
EarthSurfaceOperationControlSrcPort = 40001
;5971NG 采样模式 0 常规 1定时 = 
5971SampleType = 0
;5971NG 定时采样间隔时间 = 
5971TimeInterval = 60
;当前回收使用类型 0 网络 1 文件 = 
RebackType = 0
;该文件配置用于记录临时状态，或过程中需要更改的项 = 
;是否用户停止 = 
UserStop =0
;软件自启动工作是否设置成功(与监测工具结合使用) = 
IsSoftWareStartAutoWork =0
;slb 21.9.18 0-软件处理数据异常 = 
ProcessSampleData = 1
;是否使用默认颜色 = 
DefaultColor =0
Color =-901815|-544239|-12749837|-12528801|-6472205|-697426|-468730|-12735757|-16352466|-11730023|-883394|-16658961|-5386747|-16204383|-6524490|-7140780
;上次进行阶次分析的时间 = 
OrderResultTime = 0
;是否存在阶次分析 = 
IsExistOrder = 0
;UDP绑定的电脑IP地址 = 
BindIPAddr = 

OnlineOut = 1
;无线网络 = 
Wireless = 0
;是否离线采集标志 0没有√离线采集 1√选了离线采集 = 
OfflineSampleStatus = 0
;是否分组功能 = 
UseTeam = 0
;高速采集 = 
HighSpeedSample = 0
;千兆互连 = 
MultiKilo = 0
;主机Ip = 
MainIP = 

L = 0
Gama = 0
R = 0
T0 = 0
;管理员账户,密码 = 
AdminName = admin
AdminPassword = admin
;5916L同步时间 = 
HourMinuteSecond5916L = 8,0,0
StoreValueSec5908D = 0
;西核所离线是否使用定时 = 
IsUseOfflineTiming = 1
;GPS串口输出状态 = 
GPSOutputStatus = 0

MoogOutType = 1
;SD卡路径 = 
SDPath = C:\
;叶片疲劳参数设置 = 
StrainChnId = 1
StrainIp = 192.168.1.2
MinPPV = 0
;实时发送数据到数据中心 = 
RealTimeSendDataToDataCenter = 0
;沈阳黎明发动机测试 合格标准 = 
AcceptableQuality = ,,
;火车触发信号触发是否自动上传 = 
IsTrainTrigUpLoad = 1
ExtTrigKeepTime = 1
;是否使用GPS定时采样 = 
UseGPSTiming = 0
;记录GPS定时采样时间 = 
GPSTimingValue = 

AdjustSourceType = 1
StrainPort = 0
StrainBoundRate = 9600
AglientPort = 0
AglientIP = 192.168.0.88
;万用表 = 
Multimeter = 0
UseAgilent = 0
43018A_IP = 
DH43018ARunMode = 0
;网口类程控应变源的监听端口 = 
NetListenPort = 43020
;是否使用多路万用表，2025A03024定制，目前只针对网口万用表，后续应该也可用于常规 houzhu 2025.5.15 = 
UseMultiMultimeter = 0
;多路万用表的IP地址，以,分隔，例如192.168.0.97,192.168.0.98 = 
MultiMultimeterIP = 

IsAutoOfflineSample5916 = 0
;GPS轨迹图是否已导入地图 = 
IsImportMap = 0
;GPS轨迹图导入文件目录 = 
GPSExportDictionary = C:\Program Files\DHDAS\config\DefaultMap
;GPS轨迹图类型(0,仅在线；1，在线&离线；2，仅离线) = 
GpsAccessMode = 1
;是否需要注册用于Word导出的那些ActiveX控件 = 
;2018/4/9修改 C#组件由安装包注册,代码不负责注册,修改Word导出不正确的问题 = 
IsRegAX = 1
;要注册的ActiveX控件,也就是当前WORD导出支持的视图 = 
AXes = dhiwd,BarChat,DigitalChat,MeterChat,RecorderChat,TableChat,TimeDumpChat,TwoDChat,XYRecorderChat,ModelChat

FirstRollAngle = 0
FirstPitchAngle = 0
;视图网格X,Y = 
XScaleCount = 4
YScaleCount = 4

SFTestObj = 0
SFTestObjName = 
SFLoginUserName = 

ManageServerIP = 192.168.100.111
ManageServerPort = 38082
;5905G 是否使用休眠后 继续采样的模式 = 
IsWakeSample = 0
;三方发数tcp模式，0是服务端，1是客户端，niyang，21.7.20 = 
TCPSend = 0
;数字表等是否使用声音报警，0 否，1是   lz 21.7.22 = 
IsSupportAudioAlarm = 0
;各个等级的报警声音路径 lz 21.7.22 = 
AudioAlarmFilesPath = 
;5698B 是否回收数据从文件 hl 21.8.7 = 
IsRebackDataFromFile = 0
;5698B 是否使用中频基带获取数据流程	hl 21.8.20 = 
IsUseBandNet = 0
;5698B 是否为测试字节误码率	hl 21.9.29 = 
IsTestBandError = 0
;5953 系列与软件连接使用模式 hl 24.5.22 = 
5953TUseType = 0

ZKDefIndex = 1
ZKPower1 = 0
ZKPower2 = 0
ZKPower3 = 0
ZKPower4 = 0
ZKFreq1 = 1000
ZKFreq2 = 1000
ZKFreq3 = 1000
ZKFreq4 = 1000
ZKInstr1 = 246
ZKInstr2 = 246
ZKInstr3 = 247
ZKInstr4 = 247
;是否分时间段回收 = 
IsParagraphReback = 0
;5908D开始时间 = 
ParagraphStartTime = 
;5908D结束时间 = 
ParagraphStopTime = 
;7007电子负载配置 = 
;是否记录发送的命令 = 
IsSaveElectronicCommand = 0
;电子负载类型 1.电子负载 2.枡水科技定制 = 
ElectronicType = 1
;IP = 
ElectronicLoadIP = 192.168.200.100
;端口 = 
ElectronicLoadPort = 30000
;是否开启外部模拟量 = 
ElectronicLoadExternal = 0
;是否开启电子负载 = 
ElectronicLoadInput = 0
;电子负载模式 1:CC 2:CR 3:CV 4:CP = 
ElectronicLoadMode = 1
;最大工作电流 A = 
ElectronicLoadCurrentRange = 16
;大电流量程 A = 
ElectronicLoadCurrentRangeMax = 840
;中电流量程 A = 
ElectronicLoadCurrentRangeMiddle = 84
;小电流量程 A = 
ElectronicLoadCurrentRangeMin = 84
;电流量程 1 = 小量程 2=大量程 3=中量程
ElectronicLoadCurrentRangeMode = 1
;电流量程设置模式：0直接设置电流值 1使用小中大量程的命令 = 
ElectronicLoadCurrentRangeSetType = 0
;最大工作电压 V = 
ElectronicLoadVoltageRange = 1200
;电流电压读取间隔 ms = 
ElectronicLoadReadInterval = 200
;发送命令间隔 ms = 
ElectronicLoadCMDInterval = 100
;是否合并发送指令 1开启 0关闭 = 
ElectronicLoadCMDCombine = 1
;枡水科技定制相关参数 = 
;电流设置 = 
ElectronicCurrentValue = 5
;输出开关 1.开始直流输出 0.关闭 = 
ElectronicOutput = 0
;是否自定义版本 = 
CustomVersion = 0
;版本 = 
Version = 
;最后一次设置的数字表小数位数 = 
LastDigitalChartDecimalCount = 3
;VC参考曲线颜色 = 
VCReferLinesColor = -65536
;DH5981H DADAS中当前软件的采集状态  1开始采样  0 结束采样 = 
DHDASCurrentSampleStatus = 0
;DH5981H 当前采样测试存储路径 = 
DHDASCurrentSaveRunPath = ""
;DH5981H 当前网络发数存储路径 = 
DHDASSaveTransDatasPath = ""
;15215H应变计算系数(1) = 
;灵敏度(1号机) = 
Sensity1 = 2
;内径(1号机) = 
Neijing1 = 0
;外径(1号机) = 
Waijing1 = 1
;弹性模量 (1号机) = 
Elastic1 = 1
;泊松比 (1号机) = 
Poisson1 = 0.28
;灵敏度(2号机) = 
Sensity2 = 2
;内径(2号机) = 
Neijing2 = 0
;外径(2号机) = 
Waijing2 = 1
;弹性模量 (2号机) = 
Elastic2 = 1
;泊松比 (2号机) = 
Poisson2 = 0.28
;15215H应变计算系数(2) = 
;灵敏度(4号机) = 
Sensity3 = 2.0
;内径(4号机) = 
Neijing3 = 0
;外径(4号机) = 
Waijing3 = 1.0
;弹性模量 (4号机) = 
Elastic3 = 1.0
;泊松比 (4号机) = 
Poisson3 = 0.28
;灵敏度(5号机) = 
Sensity4 = 2.0
;内径(5号机) = 
Neijing4 = 0
;外径(5号机) = 
Waijing4 = 1.0
;弹性模量 (5号机) = 
Elastic4 = 1.0
;泊松比 (5号机) = 
Poisson4 = 0.28
;15215H仪器分组 = 
15215HMac1 = 192.168.0.103
15215HMac2 = 192.168.0.101
15215HMac3 = 192.168.0.98
15215HMac4 = 192.168.0.104
15215HMac5 = 192.168.0.112
15215HMac6 = 192.168.0.97
;停止采样时是否写入信息到日志 lz 2022.2.7 = 
IsWriteStopSampleInfo = 0
;Modbus外部数据源 数据解析方法 0:float 34121:float 1234 2:float 4321 3: float 2143 4:int 3412 5:int 1234 = 
;6:int 4321 7:int  2143 8:short 12 9:short 21 = 
ModbusOutParseType = 3
;Modbus外部数据源 发送时间间隔ms = 
ModbusOutSendTime = 100
;Modbus外部数据源 挑选通道 = 
ModbusOutSelect = 0,1,2,3,4
;ModbusTCP外部数据源(0:客户端 1:服务端) = 
ModbusOutNetType = 0
;静载小数位数,第一个值是测量类型(-1代表默认测量类型),第二个值代表小数位数 = 
StaticDigitalCount = -1,1
;数据库触发相关 = 
DBIP = 192.168.2.63
;数据库服务名 = 
DBServerName = SQLEXPRESS
;数据库名 = 
DBName = DONGLIBAOZHANG
;用户名 = 
DBUserName = DONGLIBAOZHANG
;密码 = 
DBPassword = admin123
;表名 = 
TableName = dbo.syks
;需要查询的表头, 逗号隔开 = 
TableColumn = id,_NAME,Serial,Ma,P0,T0,YB02,AYB8,AYB11,_TIMESTAMP
;表头别名, 逗号隔开, 个数与TableColumn一一对应, 如果为空字符则名称不变 = 
TableColumnAlias = id,NAME,Serial,Ma,P0,T0,YB02,AYB8,AYB11,TIMESTAMP
;读取间隔 = 
DBReadInterval = 1000
IsSort = 1
;下面这3个字段是用于逻辑判断的, 请确保字段(表头)名称没有错误, id增加之后 _NAME的值为 FieldNameValue内容时会触发采样 = 
FieldID = id
FieldName = _NAME
FieldTime = _TIMESTAMP
;_NAME字段值为配置值才会触发 = 
FieldNameValue = FD.30.syks
;横向灵敏度配置,gjd,2022.7.9 = 
8302SignalSourceSampleTime = 0
HorsensiSampleTime = 0.9
HorsensiStartDealTime = 0.2
HorsensiWaitTime = 0.2
;横向灵敏度，记录仪显示数据量 = 
HorsensiRecordDataCount = 1024
;横向灵敏度，XY记录仪显示数据量 = 
HorsensiXYRecordDataCount = 64
;横向灵敏度，正交，校准结果显示数据量 = 
HorsensiResultDataCount = 100
;电化学7007 批量导出新需求 = 
MultiExportPath = 
MultiExportType = 0
;频域统计追踪转速点数 = 
FFTStatTachoCount = 5
;5960N 特殊大数据量采集数据处理（与客户端+特殊显示端一起使用模式）显示端连接仪器端口号+网段 zs 22.11.19 = 
CSManyData_SpecialShow_NetPort = 5922
CSManyData_SpecialShow_NetSection = 0
;超然是否应用主题模式 = 
IsUseThemeMode = 0
ThemeDefault = 默认主题
ThemeBlack = 主题1
ThemeWhite = 主题2
LineNameList1D = 默认,记录仪,1D
LineNameList2D = 默认,云图,2D
LineNameList3D = 默认,模型,3D
XAxisNameList = 默认,X轴1,X轴2
YAxisNameList = 默认,Y轴1,Y轴2
ZAxisNameList = 默认,Z轴1,Z轴2
;厦门忻德静力水准仪,东华南楼应变沉降 = 
StaticForceDevID = 3,4,23,

IsElecUseJumpData = 0
ElecMaxSreenCount = 25000
;为7000L特殊添加 yangzhen 定制 2023/5/31 = 
IsUseSubjionChannel = 1
;大赛璐定制 = 
DaicelTCPPort = 33333
DaicelErrorPercent = 0
DaicelCurrentRecipe = EGK
DaicelRecipeList = EGK;EGF;EGE
DaicelUplimit = 0,0,0,0;0,0,0,0;0,0,0,0
DaicelDownlimit = 0,0,0,0;0,0,0,0;0,0,0,0
;山东亚盛PLC配置 = 
;0:TCP 1: 串口 = 
YSTYPE = 0
;山东亚盛 Modbus端口 = 
YSPort = 
;山东亚盛 Modbus波特率 = 
YSBaud = 9600
;山东亚盛 Modbus校验 = 
YSParity = None
;山东亚盛 Modbus数据位 = 
YSDataBit = 8
;山东亚盛 Modbus停止位 = 
YSStopBit = 1
;山东亚盛 Modbus站号 = 
YSSlaveAddr = 1
;山东亚盛 当前截割次数地址 = 
YSCurrentAddr = 10
;山东亚盛 总截割次数地址 = 
YSTotalAddr = 11
;IP地址 = 
YSTCPIP = 127.0.0.1
;山东亚盛 TCP端口 = 
YSTCPPort = 502
;5995卡滞灯对应值 = 
StuckValue = 1100
;5995非卡滞灯对应值 = 
UnstuckValue = 11
;3D视图自动刻度补偿值  格式：最大值补偿,最小值补偿  处理：最大值+最大值补偿， 最小值-最小值补偿 = 
ZRepairValue = 3,3
;3DDX11数据量限制 = 
ThreeDPointsLimit = 1000,1000
;3DDX11自动量程比例 = 
ThreedAutoZMinCoief = 0.8
ThreedAutoZMaxCoief = 1.2
;3DDX11缩略图大小 = 
ThreeDThumbnailWidth = 200
ThreeDThumbnailHeight = 185
;3D光标信息只显示幅值 = 
ThreeDCursorOnlyShowAmp = 0
;成都天翔动力频谱导出峰值数 = 
TianXiangFFTPeakCount = 10
;5995电源开关状态 = 
DH5995PowerStatus = 0
;5921 外时钟类型 0 不支持和 1 外时钟1 2 外时钟2 湖南航发使用 hl 23.08.29 = 
OutClockType = 0
;四川公堪院特殊协议识别码 lulj 23.12.29 = 
SpecialProtocolIdentifyCode = DH5971_12345678
;CS显示端-主控端，数据从采集端获取 网段 = 
CSShow_DataFromClient_NetSection = 0
;MTS文件解析数据特殊处理 SIGID:解析类型  0-of提取；1-Low/High = 
MTSParseValueKey = 19455619:1|19455620:1|943955:0|94395551:0
MTSTrigSignal = 19455619
MTSETrigSignal = 19455620
MTSDataFile = E:\项目需求\2024\0204-16000\16000data.dat
;增加单独线程监控MTS文件 = 
MTSMonitorFile = 0
;Rs422信号是否可以在表格上面多选，yangzhen,2024.2.3 为7951B添加，可以作为常规 = 
IsTableSupportComMultiSelect = 0
;是否改变所有曲线颜色 = 
IsChangeAllLineColor = 0
;624所自定义报告输出表格行数 = 
Report624TableRowCount = 200
;数据回收类型选择,为3818WYGC添加，yangzhen,特殊定制,2024/1/11 = 
RebackDataType_3818WYGC = 0
;分析下通道界面每页显示通道数 = 
PerChannelPageShowCount = 500
;天津中核翻页每页信号数 = 
TianJinZHEveryPageCount = 4
;数字跟踪滤波实时分析和事后分析n = 
OnlineTraceFFTN = 4
AnalysisTraceFFTN = 200
;5953Q_16||5980_BY开始时间结束时间 = 
StartTime5953Q_16 = 2024_06_01_00_00_00
EndTime5953Q_16 = 2024_06_02_00_00_00
;CS模式下，主控端或者显示端绑定IP的个数，常规，2024/8/8，yangzhen = 
CSBindIpCount = 0
CSBindIP1 = 
;9院4所分布式网络测试启动界面参数 = 
;软件名称字体大小 = 
SoftNameFontSize = 100
;软件英文名称字体大小 = 
SoftNameEngFontSize = 75
;软件中英文名称上下间距 = 
SoftNameMargin = 55
;软件名称颜色 = 
SoftNameColor = FF0057a6
;设计、制作字体大小 = 
CopyRightFontSize = 30
;初始化状态字体 = 
InfoFontSize = 25
;DHlogo区域大小 (x起点, y起点, 宽度, 高度) = 
LogoRectange = 10,10,500,100
;9院logo区域大小 (x起点, y起点, 宽度, 高度) = 
CustomLogoRectange = 20,20,500,300
;电化学分页机制，一页最大显示行数 wangwc 24.8.26 = 
ECAnalysisMaxRowCount = 1000
;7951GC三相电压值与220差值的绝对值范围 wangwc 24.8.30 = 
Monitor7951AbsolutionRange = 5

IsTorqueKNM = 0
;定位光标字体大小 = 
LocateCursorFontSize = 8
;程控校准箱相关配置 houzhu 24.9.5 = 
;是否使用程控校准箱 = 
UseCalibrationBox = 0
;使用的程控校准箱的类型 = 
CalibrationBoxType = 16
;网口的程控校准箱监听端口，根据类型区分 = 
CalibrationBoxListenPort_16 = 1234
CalibrationBoxListenPort_18 = 5675
;电化学积分边框颜色,填充颜色 (ARGB) = 
IntegralBorderColor = FFA52A2A
IntegralFillColor = FFADD8E6
;529厂定制启动软件 = 
CustomProcessStartCount = 0
CustomProcessPath1 = 
CustomProcessPath2 = 
;UNV特殊格式 = 
IsUNV = 0
;txt文件导入格式(0:无效|1:空空导弹|2:商发) = 
TXTParseType = 0
;txt文件导入大小上限（单位为MB） = 
ImportTxtMaxSize = 600
;窄带随机滤波,采样频率参数 = 
SignalSourceFilterFreq = 192000
;窄带随机滤波,校验滤波器点数 = 
SignalSourceFilterCheckDataCount = 10000
;窄带随机/猝发窄带随机,启动与结束缓变时间 = 
;是否启用缓变时间 = 
UseSignalCoeff = 0
;启动缓变时间 = 
SignalStartCoeff = 25000
;结束缓变时间 = 
SignalStopCoeff = 25000
;商发-单通道数据处理：当数据处理异常/来不及时， = 
BkOriginDataWhenError = 0
;商发-单通道数据处理：当数据处理异常/来不及时，备份原始数据-保存路径 = 
BkOriginDataPath = 
;是否为特殊波德图 = 
IsSpecialBorder = 0
;商发第三方发数小工具服务端口 = 
ControlThirdPartPort = 5008
;zhuyue 2025.4.12 江苏新扬新材料股份有限公司仪表盘定制显示 = 
IsMeterFixedCoor = 0
;7950F 隐藏测试按钮 = 
IsHide7950FTest = 0
;7953任务控制权限登录密码哈希值 zey 2025.4.22 = 
PasswordHashCode_7953 = 
;7953任务控制权限模式非对称密钥 zey 2025.4.22 = 
SecretKey_7953 = 
;江苏智仁景行存入配置 = 
StrainFreq = 0
DistanceFreq = 0
SrainParam = 0
DistanceParam = 0
MultiTrig.MultiTrigger_5916 = 0
;隐藏右上角仪器设置 = 
IsHideInterfaceSetting = 0

TrigDataCount = 40
WakeTimeMin = 60
OutTrigPDTime = 0
;试飞院实时输出文件夹路径 = 
BSWAOnlineOutputDir = D:\试飞院实时输出
;7007定制调用第三方接口位置 = 
ThirdPartExePath = D:\文件夹\函数.exe
;7007定制增加调用第三方接口 = 
Is7007LoadThirdPartExe = 0
;中国船舶科学研究中心 定制DH5902N，配置中仪器的开关机状态（在线） = 
DeviceOnlineCount = 0
;格式：ip地址|机号(从0开始) = 
DeviceOnline0 = 192.168.0.29|0
;成飞自动量程刷新间隔：ms = 
CFAutoRandRefreshInterval = 500
;武汉理工大学5710-1盒子控制5902N远程开关机功能 = 
5710_1ControlCount = 0
;控制盒1信息 格式：控制盒ip地址|仪器ip地址|机号(从0开始) = 
5710_1Control0 = 192.168.0.97|192.168.0.194|0
5710_1Control1 = 192.168.0.98|192.168.0.195|1
;江苏新扬报警视图最大显示信息数 = 
XYMaxShowAlarmCount = 1000
;623UDP定制 = 
IsEnable623UDP = 0
623UDPServerPort = 10000
623UDPClientIP = 192.168.100.118
623UDPClientPort = 20000
;红阳厂输出调试 = 
IsHYCOutputTest = 0
;5696H8B环境变量 = 
5696H8BEnvVariable = 
;5981C_64仪器模式 0：正常模式  1：调试模式 = 
DeviceMode5981C_64 = 0
;是否同时传输断点数据，实时回收丢包数据 = 
UseRealTimeRebackLost = 
;西安倍得新模式 0:常规测量系统软件 1:模型压力测量系统软件 2:脉动压力测量系统软件 = 
XianBDXWorkMode = 0
;浙江季丰同步时钟盒设置type[0]- type[7]对应端口1-8  输出类型  0x00：DH5960J   0x01：DH8303 = 
5611IMulti_OutValue = 0,0,0,0,1,1,1,1
;电化学系数 = 
EISCoief = 0,0

;某基地同步时钟控制器设置type[0]- type[7]对应端口1-8  输出类型  0x00：DH8300N   0x01：DH8301N  0x02：DH8302 = 
5611F_8_Multi_OutValue = 2,2,2,1,1,1,0,0
;某基地同步时钟控制器设置时序输出参数 输出类型，幅值，延迟，方波频率，方波脉宽，输出端口 = 
5611F_8_SequenceOutParam = 0,3,1,1000,1,3
;某基地同步时钟控制器输出使能控制 type[0]- type[7]对应端口1-8，0关闭，1输出 = 
5611F_8_EnabledOutControl = 0,0,0,0,0,0,0,0
;调理器相关配置 = 
GainSleepTime = 1000
DCSleepTime = 0
ChangeValueSleepTime = 500
ClearZeroSleepTime = 500
SetCoiefSleepTime = 500
BalanceSleepTime = 10000
DebugGain = 0
GainInputReadCount = 5
GainOutputReadCount = 5
;某基地同步时钟控制器定义主控端客户端命令发送端口号 = 
5611F_8_Port = 5611
;核工业PLC相关设置 = 
BDXCPU = 4
BDXIP = 192.168.0.100
BDXRack = 0
BDXSlot = 1
BDXAddress = DB11.DBW0,DB11.DBD2,DB11.DBX6.0,DB11.DBD8,DB11.DBD12,DB11.DBD16,DB11.DBD20,DB11.DBX24.0,DB11.DBX24.1,DB11.DBX6.1
BDXCHN1 = 
BDXCHN2 = 
BDXCHN3 = 
BDXCHN4 = 

IsHTKGDigitalChat = 0
SelectNetName=以太网
