[SystemParameter]
InstrumentType=773

InterfaceType=8
; 0(EPP);1(1394);2(USB);3(Rs232);4(Demo);5(EISA);6(NET);7(千兆网);8(4G);9(PCI);10(EtherCAT)

;多仪器分组
MultiHardWareManage=0 
;分组数
MultiHardWareManageCount=0

;调试
Debug=0
;是否需要同步时钟
UseClock=1
;同步模式: 0-常规同步5611同步;1-GPS同步;2-1588同步;3-DH5611-1同步;4-级联同步
ClockType=0

;是否高低速采样
SupportHLSample=0

;可以连接的CS端最大个数,常规，2024/8/8，yangzhen
CSMaxCount=5

;是否支持NTP同步
NTPSync=0
;支持moog功能
SupportMoog=0

;成飞加载系统
MTS = 0

;是否支持用户管理
IsSupportUserMgr=0

;当前是否在使用5907M监测软件
IsMonitor5709=0

IsAdministrator=1

OutMinTime=0.1
OutMaxTime = 0.5
;热电偶通道可以使用电压通道做补偿
UseVltChnRepair=0

;输出log等级，小于该等级的都会输出 none = 0,fatal = 1,error = 2,warning = 3,info = 4,debug = 5,verbose = 6
pLogLevel=2
;每个log文件的大小
pLogSize=5242880
;最大的log文件数
pLogNumber=50
;输出log的方式，写文件 = 0,控制台输出 = 1, 同时写文件和控制台输出 = 2
pLogType = 0

;键相触发是否固定某个通道
IsTachoPhaseFixedChannel = 0
