[SystemParameter]
;该配置文件只能读取，软件打开过程中不允许写入，保证该文件不被破坏

;常态电阻计算常量
RStatic=0.1
;常态电阻超限值
RStaticLimit=1000
;0:如果电流通道有负值则使用RStaticLimit作为结果   1:如果电流通道有负值则剔除负值计算平均值
OnlyUsePositive=0
;电容计算常量
R1=100000
R2=100000
;周期数
M=16
;绝缘电阻计算常量
RInsulation=16000
;绝缘电阻零点值
RInsulationZeroValue=-28
;绝缘电阻超限值
RInsulationLimit=1000
;震动测量灵敏度计算块大小
LinearBlockSize=1024

;电容单位系数
CapacitanceCoief=1000000000000
;电容补偿值(减)
CapacitanceRepairValue=0
;绝缘电阻单位系数
RInsulationCoief=1000000

;采样频率
LinearFreq=200000
RFreq=20000
CFreq=20000
InsulationFreq=20000
;电容信号频率
CSignalFreq=1250
;采样时间
LinearSampleTime=10000
RCSampleTime=400
InsulationSampleTime=400
;使用点数 常态电阻、绝缘电阻计算时需要的数据量
DataCount=1000

;信号源开始频率
SignalSourceStartFreq=1
SignalSourceEndFreq=20000
;信号源实际开始频率
SignalSourceRealStartFreq=4000
;信号源扫速
SignalSourceStep=2000
;信号源幅值
SignalSourceBreadth=7000
;信号源通道号(索引-1)
SignalSourceChannelID=14
;震动测量前是否重置信号源参数
IsResetSignalSourceParam=0

;电压量程
ChannelVolRange=200

;采集通道号
ChannelStandardIndex=0
ChannelTestIndex=1
;常态电阻通道号
ChannelSRIndex=2
;电容通道号
ChannelCIndex=3
;绝缘电阻1通道号
ChannelIR1Index=4
;绝缘电阻2通道号
ChannelIR2Index=5

;IO输入索引
DIIndex=1,2,3,8,5,6,7,0,0,10,11,12,13,14
;IO输出索引
DOIndex=23,18,20,17,0,0,7,8,0,0,1,5,2,3,4,16,24,19,21,6,22



;上下限参考曲线 连线类型 0:直线 1:短虚线 2:长虚线短间隔 3:长虚线长间隔
FitResultLineType=1
;线宽
FitResultLineWidth=2

;默认传感器类型
DefaultSensor=

;标准灵敏度
StandardSensitivity=1

;采样数据取不到超时时间(秒)
TimeoutSampleData=2
;自检传感器检测超时
TimeoutSelfCheck=3
;气缸操作超时时间(秒)
TimeoutCylinder=3
;电动扳手操作超时时间(秒)
TimeoutDDK=3
;等待废品丢弃超时(秒)
TimeoutFailProduct=10

;伺服动作等待时间
;动作1 下降到开始位置
DownStartPosWaitTime=2000
;动作2 拧紧下降
DownRotatePosWaitTime=2000
;动作3 直接下降到松开位置
DownReleasePosWaitTime=2000
;动作4 松开上升
UpReleaseWaitTime=2000
;回原点
HomeWaitTime=3000

;每一步等待时间(ms)
StepWaitTime=20

;拧紧台是否需要松螺丝
IsDDKNeedRelease=1
;是否开始之后就启动静态测量
IsStartStaticMeasureFirst=1

;扭矩配置
;COM口
Port=
;波特率
BaudRate=9600
;校验位
Parity=None
;数据位
DataBit=8
;停止位 0:不使用停止位 1:1个停止位 2:2个停止位 3: 1.5个停止位
StopBit=1
;Modbus站号
SlaveAddress=1
;实时扭矩地址
RealTorqueAddress=8421
;完成时扭矩地址
FinishedTorqueAddress=8393
;读取间隔(ms)
ReadInterval=100

;是否保存采样数据
IsSaveSampleData=1
;保留几位小数
DigitalNumber=3
;是否显示DO状态灯
IsShowDOLights=0

;完成扭矩最小值 0为不判断
MinTorqueValue=8000
;完成扭矩最大值 0为不判断
MaxTorqueValue=12000

;灵敏度测量通道最大值小于该值则灵敏度固定显示0.01
SensitivityMinValue=0.3
;SensitivityMinValue不参与判断的频率点, 逗号隔开
SensitivityIgnoreFreq=11
;1计算标准差 0 计算有效值
SensitivityAlgoType=1
;灵敏度测量结果峰峰值小于该值则认为没有振动
SensitivityMinPeakValue=5

;灵敏度特殊频率公式处理判断阈值
SpecialThreshold=1