[Parse9]
Interval = 1000;
Name = 静力水准
Count=3 ;	目前支持最大拆分通道个数40

Name0=液位值1
Unit0=mm
Detail0=

Name1=液位值2
Unit1=mm
Detail1=

Name2=液位值3
Unit2=mm
Detail2=

ModbusCount = 3  ;通道上接入的传感器种类个数

StartPos_0 = 0
DataLen_0 = 4     
MacAddr_0 = 1     
FunctionCode_0 = 3  

 ;一个Modbus传感器下的通道参数   
ModbusCount_0=1              
ModbusIndex0_0 = 0
ChnIndex0_0 = 0
ModbusParseType0_0 = 1 ;传感器上通道数据解析的类型 ;0表示解析米朗传感器位移 1表示解析静力水准

StartPos_1 = 0
DataLen_1 = 4     
MacAddr_1 = 2     
FunctionCode_1 = 3

ModbusCount_1=1
ModbusIndex1_0 = 0
ChnIndex1_0 = 1
ModbusParseType1_0 = 1 

StartPos_2 = 0
DataLen_2 = 4     
MacAddr_2 = 3     
FunctionCode_2 = 3

ModbusCount_2=1
ModbusIndex2_0 = 0
ChnIndex2_0 = 2
ModbusParseType2_0 = 1 


[Parse44]
Interval = 1000;
Name = 有线激光位移计
Count = 2
Name0 = 位移变化
Detail0 = 
Unit0 = mm
MaxValue0 = 10000
MiniValue0 = -10000
Name1 = 距离初值
Detail1 = 
Unit1 = mm
MaxValue1 = 10000
MiniValue1 = -10000

ModbusCount = 1
StartPos_0 = 0
DataLen_0 = 6
MacAddr_0 = 1
FunctionCode_0 = 4
ModbusCount_0 = 2
ModbusCheckedCount_0 = 2
ModbusName_0 = 传感器1
ModbusIndex0_0 = 0
ChnIndex0_0 = 0
ModbusParseType0_0 = 25
Unit0_0 = mm
Name0_0 = 位移变化
Detail0_0 = 
ModbusIsUsed0_0 = 1
MaxValue0_0 = 10000
MiniValue0_0 = -10000
ByteLength0_0 = 2
ModbusIndex0_1 = 2
ChnIndex0_1 = 1
ModbusParseType0_1 = 1
Unit0_1 = mm
Name0_1 = 距离初值
Detail0_1 = 
ModbusIsUsed0_1 = 1
MaxValue0_1 = 10000
MiniValue0_1 = -10000
ByteLength0_1 = 2


