[SystemParameter]
;仪器前缀(例：1号仪器=>NGC_1)
;一级代号
NGC_1-OneCode = GL001
;二级代号
NGC_1-TwoCode = GH1840076MBR3A
;设备编号
NGC_1-MachineNO = 001023
;通道编号
NGC_1-01 = WT1
NGC_1-02 = WT2
NGC_1-03 = WT3
NGC_1-04 = WT4
NGC_1-05 = WT5
NGC_1-06 = WT6
NGC_1-07 = WT7
NGC_1-08 = WT8
;5978 422通道特别配置
NGC_温度 = WT9
NGC_含水率 = WT10


