[SystemParameter]
;0常规 1离线定时 2离线连续
SampleMode=0

;离线连续采样开始时间
StartTime=2022/2/20 08:00:00
;离线连续采样结束时间
StopTime=2022/2/28 08:00:00

;采样时间 （min）
SampleTime=60
StartDate=2022/2/1
StopDate=2022/2/28
;离线定时个数
FixTimeCount=1
TimeStart0=08:00:00