
[EngineStartSignalRelation]
;状态字对应信号关系
StatusCount=8
;调试状态标识名字,AI1-01表示通道名称
Channel0=起动超温,AI1-01
Channel1=滑油压力低,AI1-02
Channel2=滑油压力高,
Channel3=高低压转子不匹配,AI1-04
Channel4=起动热悬挂,AI1-05
Channel5=点火失败,
Channel6=燃油超温,AI1-06
Channel7=油泵超压,
;通道状态
Status0=>780℃(持续时间2s)/保护温度810℃(0s)
Status1=<310kPa
Status2=>620kPa
Status3=a2>25.9%,n1无示数
Status4=None
Status5=None
Status6=None
Status7=None



