[System]
;是否测试
Debug = 0

;1小时数据
MaxBufferCount=360000

ContentType=application/json
;发送网址
TargetHostIp =http://localhost:47964/WebService1.asmx/HelloWorld
;Token =b547ca01-3481-4e3a-a796-334d63187db4
Token = 8d647c91-1f78-4f6e-942b-7718d47cc738
;发送间隔
SendInterval=3600

IsSendRealValue=1
IsSendMaxValue=1
IsSendVirValue=1












